- hosts: localhost
  roles:
     - role: cloud.azure_ops.azure_manage_resource_group
       operation: "create"
       azure_region: "eastus"
       azure_resource_group: "bpeck-tests"

- hosts: localhost
  vars:
    azure_resource_group: 'bpeck-tests'
  tasks:
     - block:
       - name: Create a load balanced virtual machine with a default network interface
         ansible.builtin.include_role:
           name: cloud.azure_ops.azure_virtual_machine_with_public_ip
         vars:
           operation: 'create'
           azure_vm:
             name: "{{ azure_resource_group }}-example-vm"
             admin_username: 'azureuser'
             admin_password: "{{ azure_admin_password }}"
             image:
               offer: RHEL
               publisher: RedHat
               sku: 7-LVM
               version: latest
             size: Standard_DS1_v2
             load_balancer_backend_address_pools:
               - name: 'default'
                 load_balancer: 'existing-lb'
       rescue:
         - name: Get facts for all resource groups
           azure.azcollection.azure_rm_resourcegroup_info:
             name: "{{ azure_resource_group }}"
             register: rg_info
         - name: Debug Resource Group
           ansible.builtin.debug:
             var: rg_info
       always:
         - name: Delete virtual machine and all autocreated resources
           ansible.builtin.include_role:
             name: cloud.azure_ops.azure_virtual_machine_with_public_ip
           vars:
             operation: "delete"
             remove_on_absent: 'all_autocreated'
             azure_vm:
               name: "{{ azure_resource_group }}-example-vm"
